# NYC_Payroll_EDA 2

In [19]:
import pandas as pd
import numpy as np

# load data into a dataframe
payroll_df = pd.read_csv('Citywide_Payroll_Data__Fiscal_Year_.csv',dtype='str')

In [10]:
# Drop the duplicated records.
payroll_df = payroll_df.drop_duplicates()

In [11]:
payroll_df

,Fiscal Year,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay
0,2016,DISTRICT ATTORNEY-MANHATTAN,ABA'AHMID,RAHASHEEM,E,07/14/2003,MANHATTAN,COMMUNITY ASSOCIATE ...,ACTIVE,$47678.00,per Annum,1830,$47166.03,2.25,$57.28,$0.00
1,2016,DISTRICT ATTORNEY-MANHATTAN,ABENSUR,MARGARET,NaN,06/12/1995,MANHATTAN,ADMINISTRATIVE ACCOUNTANT ...,ACTIVE,$119959.00,per Annum,1831,$119042.50,0,$0.00,$0.00
2,2016,DISTRICT ATTORNEY-MANHATTAN,ABOUNAOUM,ANDREA,L,10/11/2011,MANHATTAN,COMMUNITY ASSOCIATE ...,ON LEAVE,$39966.00,per Annum,1181.68,$27452.62,1,$21.34,$33.00
3,2016,DISTRICT ATTORNEY-MANHATTAN,ABRAHAM,JONATHAN,J,12/01/2014,MANHATTAN,COMPUTER SYSTEMS MANAGER ...,ACTIVE,$116000.00,per Annum,1831,$115104.57,0,$0.00,$0.00
4,2016,DISTRICT ATTORNEY-MANHATTAN,ABRAMS,JOSEPH,NaN,05/21/2015,MANHATTAN,COLLEGE AIDE ...,CEASED,$1.00,per Hour,0,$3500.00,0,$0.00,$0.00
5,2016,DISTRICT ATTORNEY-MANHATTAN,ABREU,JENNIFER,NaN,09/04/2012,MANHATTAN,ASSISTANT DISTRICT ATTORNEY ...,ACTIVE,$71500.00,per Annum,1831,$71967.34,0,$0.00,$0.00
6,2016,DISTRICT ATTORNEY-MANHATTAN,ABREU,JUAN,D,09/04/2007,MANHATTAN,ASSISTANT DISTRICT ATTORNEY ...,ACTIVE,$88000.00,per Annum,1831,$87614.01,0,$0.00,$750.00
7,2016,DISTRICT ATTORNEY-MANHATTAN,ACEVEDO,JENNIFER,NaN,06/06/2016,MANHATTAN,COLLEGE AIDE ...,ACTIVE,$1.00,per Hour,0,$500.00,0,$0.00,$0.00
8,2016,DISTRICT ATTORNEY-MANHATTAN,ACOCELLA,MATTHEW,J,09/02/2014,MANHATTAN,COMMUNITY ASSOCIATE ...,CEASED,$41000.00,per Annum,349,$9507.15,0,$0.00,$0.00
9,2016,DISTRICT ATTORNEY-MANHATTAN,ACOSTA,RITA,E,05/31/1978,MANHATTAN,PRINCIPAL ADMINISTRATIVE ASSOCIATE,ACTIVE,$66035.00,per Annum,1830,$64357.12,0,$0.00,$3824.72
10,2016,DISTRICT ATTORNEY-MANHATTAN,ADAMS,KATHERINE,J,04/22/2013,MANHATTAN,COMMUNITY ASSOCIATE ...,CEASED,$38869.00,per Annum,200.7,$6073.13,0,$0.00,$8.25
11,2016,DISTRICT ATTORNEY-MANHATTAN,ADAMS,NEERESHA,NaN,08/25/2014,MANHATTAN,COMMUNITY ASSOCIATE ...,ACTIVE,$42075.00,per Annum,1830,$39895.79,0,$0.00,$74.25
12,2016,DISTRICT ATTORNEY-MANHATTAN,ADEGBORO,OYINDAMOLA,F,01/13/2014,MANHATTAN,COMMUNITY COORDINATOR ...,ACTIVE,$66625.00,per Annum,1830,$65909.63,0,$0.00,$33.00
13,2016,DISTRICT ATTORNEY-MANHATTAN,AGGARWAL,SANCHITA,J,03/28/2005,MANHATTAN,PRINCIPAL ACCOUNTANT INVESTIGATOR ...,ACTIVE,$112592.00,per Annum,1831,$111806.82,0,$0.00,$500.00
14,2016,DISTRICT ATTORNEY-MANHATTAN,AGUILAR,YAMIRA,NaN,11/09/2009,MANHATTAN,COMMUNITY ASSOCIATE ...,ACTIVE,$52548.00,per Annum,1830,$51890.77,716.25,$25943.55,$747.93
15,2016,DISTRICT ATTORNEY-MANHATTAN,AGUIRRE,JORDAN,NaN,05/21/2015,MANHATTAN,COLLEGE AIDE ...,CEASED,$1.00,per Hour,0,$3500.00,0,$0.00,$0.00
16,2016,DISTRICT ATTORNEY-MANHATTAN,AHMETAJ,ARTEMIS,NaN,04/28/2014,MANHATTAN,COMMUNITY ASSISTANT ...,ACTIVE,$43299.00,per Annum,1830,$40052.01,51.75,$1413.40,$526.11
17,2016,DISTRICT ATTORNEY-MANHATTAN,AHN,HELEN,H,09/07/2004,MANHATTAN,ASSISTANT DISTRICT ATTORNEY ...,ACTIVE,$102500.00,per Annum,1076,$59023.02,0,$0.00,$0.00
18,2016,DISTRICT ATTORNEY-MANHATTAN,ALCAIDE,SANDRA,NaN,05/21/2015,MANHATTAN,COLLEGE AIDE ...,CEASED,$1.00,per Hour,0,$3500.00,0,$0.00,$0.00
19,2016,DISTRICT ATTORNEY-MANHATTAN,ALCANTARA,DANIEL,NaN,01/19/2007,MANHATTAN,COMMUNITY ASSOCIATE ...,ACTIVE,$40299.00,per Annum,1830,$39866.21,0,$0.00,$0.00
20,2016,DISTRICT ATTORNEY-MANHATTAN,ALEXANDER,ERIN,L,09/02/2014,MANHATTAN,ASSISTANT DISTRICT ATTORNEY ...,ACTIVE,$78000.00,per Annum,1509,$64498.36,0,$0.00,$1750.00
21,2016,DISTRICT ATTORNEY-MANHATTAN,ALFLEN,PAUL,R,09/21/2008,MANHATTAN,CARPENTER ...,ACTIVE,$370.16,per Day,1830,$139072.14,408.75,$50546.28,$5060.37
22,2016,DISTRICT ATTORNEY-MANHATTAN,ALI,SHEHARYAR,NaN,06/06/2016,MANHATTAN,COLLEGE AIDE ...,ACTIVE,$1.00,per Hour,0,$1000.00,0,$0.00,$0.00
23,2016,DISTRICT ATTORNEY-MANHATTAN,ALI,SYEED,A,03/02/2009,MANHATTAN,ELECTRICIAN'S HELPER ...,ACTIVE,$217.70,per Day,1830,$56602.00,173.75,$8991.82,$7424.72
24,2016,DISTRICT ATTORNEY-MANHATTAN,AL-KAABAH II,JEFFREY,I,06/08/2015,MANHATTAN,COMMUNITY ASSOCIATE ...,ACTIVE,$53366.00,per Annum,1829.75,$46271.84,276.5,$7757.06,$755.84
25,2016,DISTRICT ATTORNEY-MANHATTAN,NaN,NaN,NaN,08/06/2001,MANHATTAN,RACKETS INVESTIGATOR,CEASED,$59945.00,per Annum,0,$7412.58,0,$13.01,$340.12
26,2016,DISTRICT ATTORNEY-MANHATTAN,ALKHAFAJEE,ABEER,K,08/16/2010,MANHATTAN,COMMUNITY ASSOCIATE ...,CEASED,$45985.00,per Annum,38.1,$4661.03,1,$169.90,$94.40
27,2016,DISTRICT ATTORNEY-MANHATTAN,ALKHAFAJEE,SHAIMAA,NaN,01/14/2008,MANHATTAN,COMMUNITY ASSISTANT ...,ACTIVE,$36154.00,per Annum,1830,$35765.73,0,$0.00,$0.00
28,2016,DISTRICT ATTORNEY-MANHATTAN,ALLEN,BENNETT,L,10/20/2014,MANHATTAN,COMMUNITY COORDINATOR ...,ACTIVE,$65600.00,per Annum,1830,$64895.59,0,$0.00,$99.50
29,2016,DISTRICT ATTORNEY-MANHATTAN,ALLEN,ROBERT,K,01/21/1980,MANHATTAN,CLERICAL ASSOCIATE,ACTIVE,$56017.00,per Annum,1830,$55411.18,0,$0.00,$4424.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2194458,2017,DISTRICT ATTORNEY-SPECIAL NARC,BACH,CAROL,M,02/06/1995,MANHATTAN,REPORTER/ STENOGRAPHER ...,ACTIVE,$76906.00,per Annum,745,$35037.96,0,$0.00,$1392.26
2194459,2017,DISTRICT ATTORNEY-SPECIAL NARC,ARNOLD,JODI,A,06/02/2008,MANHATTAN,REPORTER/ STENOGRAPHER ...,ACTIVE,$70107.00,per Annum,1795,$78899.33,0,$293.87,$1034.00
2194460,2017,DISTRICT ATTORNEY-SPECIAL NARC,MONESTIME,MIREILLE,NaN,11/28/1988,MANHATTAN,REPORTER/ STENOGRAPHER ...,ACTIVE,$81465.00,per Annum,1795,$92825.55,0,$0.00,$5234.62
2194461,2017,DISTRICT ATTORNEY-SPECIAL NARC,PALMER,REVA,A,04/08/1985,MANHATTAN,REPORTER/ STENOGRAPHER ...,ACTIVE,$81465.00,per Annum,1795,$92392.05,0,$0.00,$5242.87
2194462,2017,DISTRICT ATTORNEY-SPECIAL NARC,GIERAS,SUSAN,NaN,05/09/2016,MANHATTAN,REPORTER/ STENOGRAPHER ...,ACTIVE,$53930.00,per Annum,1795,$61257.09,0,$0.00,$0.00
2194463,2017,DISTRICT ATTORNEY-SPECIAL NARC,AKOTO,AKUA,P,02/22/1982,MANHATTAN,SECRETARY ...,ACTIVE,$72420.00,per Annum,1795,$78504.22,0,$0.00,$4777.75
2194464,2017,DISTRICT ATTORNEY-SPECIAL NARC,MCNEILL,BELINDA,D,05/28/1991,MANHATTAN,SECRETARY ...,ACTIVE,$62141.00,per Annum,1795,$66533.67,0,$0.00,$4794.25
2194465,2017,DISTRICT ATTORNEY-SPECIAL NARC,MOULTRIE,HYARLIEN,NaN,12/04/2000,MANHATTAN,SECRETARY ...,ACTIVE,$88799.00,per Annum,1795,$95355.97,0,$0.00,$4777.75
2194466,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,NaN,01/03/2000,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,$75281.00,per Annum,2051.43,$85707.57,59,$3458.71,$2700.42
2194467,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,A,10/06/2014,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,$62330.00,per Annum,2051.43,$72345.61,9,$425.61,$3649.49
2194468,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,A,06/06/2016,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,$59920.00,per Annum,2051.43,$62875.62,0,$0.00,$3707.68
2194469,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,V,01/22/2002,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,$82451.00,per Annum,2051.43,$90699.68,0,$0.00,$3648.99
2194470,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,J,05/01/2001,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,$88609.00,per Annum,2051.43,$99463.33,0,$0.00,$3624.24
2194471,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,NaN,02/03/2014,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,$65202.00,per Annum,2051.43,$75310.50,63,$3442.18,$3624.24
2194472,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,R,11/18/1996,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,CEASED,$82032.00,per Annum,931.43,$50750.67,0,$0.00,$1744.74
2194473,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,K,09/05/2006,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,$78643.00,per Annum,2051.43,$86779.58,0,$0.00,$3624.24
2194474,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,M,07/05/1989,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,CEASED,$78342.00,per Annum,1483.43,$110014.31,0,$0.00,$2671.02
2194475,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,R,02/27/1989,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,$79275.00,per Annum,2051.43,$89827.42,43,$3361.40,$3624.24
2194476,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,NaN,10/13/2015,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,$60000.00,per Annum,2051.43,$64925.95,8,$1283.22,$4743.09
2194477,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,NaN,02/23/1998,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,CEASED,$78634.00,per Annum,1515.43,$89040.81,0,$0.00,$2724.80
2194478,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,NaN,02/28/1994,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,$89824.00,per Annum,2051.43,$100717.56,0,$0.00,$3624.24
2194479,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,W,08/02/1982,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,CEASED,$89443.00,per Annum,0,$8620.39,0,$0.00,$133.88
2194480,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,J,02/07/2017,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,$60000.00,per Annum,792,$22783.69,0,$0.00,$8.25
2194481,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,K,11/03/2014,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,$59099.00,per Annum,2051.43,$69010.10,205,$9713.32,$84.91
2194482,2017,DISTRICT ATTORNEY-SPECIAL NARC,BRENNAN,BRIDGET,G,01/27/1992,MANHATTAN,SPECIAL ASSISTANT DISTRICT ATTORNEY ...,ACTIVE,$206416.00,per Annum,1795,$221466.24,0,$0.00,$0.00
2194483,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,G,10/02/2006,MANHATTAN,SUPERVISING RACKETS INVESTIGATOR,ACTIVE,$80643.00,per Annum,2051.43,$87321.90,113,$7667.53,$3624.24
2194484,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,C,01/18/2000,MANHATTAN,SUPERVISING RACKETS INVESTIGATOR,ACTIVE,$88883.00,per Annum,2051.43,$99746.21,117,$9491.90,$3624.24
2194485,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,NaN,03/17/1997,MANHATTAN,SUPERVISING RACKETS INVESTIGATOR,ACTIVE,$89686.00,per Annum,2051.43,$96646.24,63,$4937.42,$3624.24
2194486,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,J,04/19/1993,MANHATTAN,SUPERVISING RACKETS INVESTIGATOR,ACTIVE,$94245.00,per Annum,2051.43,$105281.70,22,$1544.83,$3624.24
2194487,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,L,02/10/1992,MANHATTAN,SUPERVISING RACKETS INVESTIGATOR,CEASED,$89780.00,per Annum,1235.43,$78923.55,160,$12509.95,$2388.87

Convert all monetary columns to numeric data type, if you haven’t done so.

Get rid of “$” and “,” in salary fields and convert them to numeric/float

In [14]:
# Convert the 'Fiscal Year' field from a string to an int
payroll_df['Fiscal Year'] = payroll_df['Fiscal Year'].astype('int64')

# Convert the fields 'Regular Hours','OT Hours' from string to float
payroll_df[['Regular Hours','OT Hours']] = payroll_df[['Regular Hours','OT Hours']].astype('float64')

In [16]:
# Convert all monetary columns to numeric data type 
payroll_df['Base Salary'] = payroll_df['Base Salary'].str.replace('$','').astype('float64')
payroll_df['Regular Gross Paid'] = payroll_df['Regular Gross Paid'].str.replace('$','').astype('float64')
payroll_df['Total OT Paid'] = payroll_df['Total OT Paid'].str.replace('$','').astype('float64')
payroll_df['Total Other Pay'] = payroll_df['Total Other Pay'].str.replace('$','').astype('float64')

In [15]:
# Convert all monetary columns to numeric data type 
for col in ['Base Salary','Regular Gross Paid','Total OT Paid','Total Other Pay']:
    payroll_df[col] = payroll_df[col].str.replace('$','').astype('float64')

In [16]:
payroll_df.dtypes

Fiscal Year                     int64
Agency Name                    object
Last Name                      object
First Name                     object
Mid Init                       object
Agency Start Date              object
Work Location Borough          object
Title Description              object
Leave Status as of June 30     object
Base Salary                   float64
Pay Basis                      object
Regular Hours                 float64
Regular Gross Paid            float64
OT Hours                      float64
Total OT Paid                 float64
Total Other Pay               float64
dtype: object

In [9]:
str_lst=pd.Series(['$5,007.28', '$0.00', '$21,000.34', '$0.00', '$0.00'])
#float_lst = []  
float_lst = str_lst.str.replace('$','').str.replace(',','').astype('float64')
#float_lst=[float(i) for i in float_lst]
float_lst

0     5007.28
1        0.00
2    21000.34
3        0.00
4        0.00
dtype: object

Create a new column “DISTRICT ATTORNEY” for all different areas “DISTRICT ATTORNEY-“, such as “DISTRICT ATTORNEY- MANHATTAN”, “BRONX DISTRICT ATTORNEY”, etc.

Sort dataframe on Regular Gross Paid

In [17]:
payroll_df.sort_values('Regular Gross Paid')

,Fiscal Year,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay
63810,2016,POLICE DEPARTMENT,TAUTE JR.,RICHARD,J,06/30/1992,MANHATTAN,POLICE OFFICER,CEASED,77253.00,per Annum,0.00,-29862.19,0.00,25167.16,5522.73
1125381,2014,OFFICE OF THE COMPTROLLER,LOCKWORTH,HENRY,L,04/30/1973,NaN,ACCOUNTANT ...,CEASED,59357.00,per Annum,0.00,-20143.36,0.00,0.00,0.00
1981727,2017,DEPT OF ED PER SESSION TEACHER,HEALY,STACEY,M,09/08/1992,MANHATTAN,TEACHER- PER SESSION ...,CEASED,33.18,per Day,0.00,-18142.17,0.00,0.00,0.00
526682,2016,NYC HOUSING AUTHORITY,CROMARTIE,JAMES,NaN,06/12/1989,MANHATTAN,MAINTENANCE WORKER ...,CEASED,218.60,per Day,102.85,-14518.42,0.00,1139.05,87.91
1544046,2014,DEPT OF PARKS & RECREATION,TROCHE,ARMAND,NaN,11/13/2012,NaN,CITY PARK WORKER ...,CEASED,14.02,per Hour,1463.65,-14233.81,42.00,-126.18,-168.24
1162799,2014,HRA/DEPT OF SOCIAL SERVICES,CALI,CHARLES,J,06/30/2004,NaN,CERTIFIED IT ADMINISTRATOR ...,CEASED,82779.00,per Annum,0.00,-13451.36,0.00,0.00,0.00
1377567,2014,DEPT OF ED PARA PROFESSIONALS,PINEDA,JOSE,NaN,04/07/2011,NaN,ANNUAL ED PARA ...,CEASED,21713.00,per Annum,0.00,-12206.64,0.00,0.00,0.00
1111219,2015,NYC HOUSING AUTHORITY,PIGNATELLI,PASQUALE,NaN,03/01/2004,MANHATTAN,PLASTERER ...,CEASED,324.72,per Day,0.00,-12039.46,0.00,0.00,0.00
196279,2016,DEPT OF ED HRLY SUPPORT STAFF,ATTRIDE,SONIA,J,11/19/2012,MANHATTAN,F/T SCHOOL LUNCH HELPER ...,CEASED,14.78,per Hour,0.00,-11507.45,0.00,0.00,0.00
2126484,2017,TEACHERS RETIREMENT SYSTEM,WALL,MARY,NaN,03/10/2003,MANHATTAN,COMPUTER SYSTEMS MANAGER ...,CEASED,153559.00,per Annum,0.00,-11240.19,0.00,0.00,0.00
661184,2015,COMMUNITY COLLEGE (KINGSBORO),KLEIN,BERNARD,NaN,07/01/1984,BROOKLYN,PROFESSOR ...,CEASED,101435.00,per Annum,0.00,-11136.13,0.00,0.00,0.00
59845,2016,POLICE DEPARTMENT,SEARS,WENDELL,T,07/08/1985,MANHATTAN,LIEUTENANT D/A SPECIAL ASSIGNMENT,CEASED,127588.00,per Annum,0.00,-10952.67,0.00,0.00,15934.45
70884,2016,DISTRICT ATTORNEY-SPECIAL NARC,BRZESKI,ERIN,NaN,09/01/2008,MANHATTAN,ASSISTANT DISTRICT ATTORNEY ...,CEASED,78000.00,per Annum,0.00,-10109.22,0.00,0.00,1000.00
1560871,2014,NYC HOUSING AUTHORITY,WEBER,STUART,NaN,04/02/1990,NaN,MAINTENANCE WORKER ...,CEASED,209.12,per Day,0.00,-9803.40,0.00,0.00,0.00
2119591,2017,NYC HOUSING AUTHORITY,VASQUEZ,VINCENT,NaN,04/06/1992,BROOKLYN,CARETAKER ...,CEASED,40804.00,per Annum,0.00,-9197.50,0.00,0.00,0.00
1109707,2015,NYC HOUSING AUTHORITY,MIDDLETON,MILDRED,L,01/21/2003,BROOKLYN,CARETAKER ...,CEASED,39803.00,per Annum,0.00,-8530.42,0.00,0.00,0.00
659993,2015,COMMUNITY COLLEGE (KINGSBORO),DAUBER,PEARL,NaN,08/20/1999,BROOKLYN,COLLEGE ASSISTANT ...,CEASED,9.16,per Hour,0.00,-8506.68,0.00,0.00,0.00
1695955,2017,COMMUNITY COLLEGE (KINGSBORO),SECONDINO,ANTHONY,L,02/02/2004,BROOKLYN,STATIONARY ENGINEER ...,CEASED,486.72,per Day,168.00,-7822.77,16.00,8583.99,14533.64
2117596,2017,NYC HOUSING AUTHORITY,RODRIGUEZ,EDGAR,NaN,06/03/1991,BRONX,HOUSING ASSISTANT ...,CEASED,57269.00,per Annum,316.25,-7562.47,0.00,0.00,199.32
251049,2016,DEPT OF ED PARA PROFESSIONALS,YIP,CHICK PUI,T,11/22/1999,MANHATTAN,ANNUAL ED PARA ...,CEASED,35040.00,per Annum,0.00,-7469.45,0.00,0.00,0.00
1567131,2014,NYC HOUSING AUTHORITY,RICH,SHARON,L,07/30/2007,NaN,CARETAKER ...,CEASED,39019.00,per Annum,32.00,-7213.70,0.00,0.00,0.00
2163398,2017,POLICE DEPARTMENT,LEMM,JOSEPH,G,03/01/2000,MANHATTAN,POLICE OFFICER D/A DETECTIVE 1ST GR ...,CEASED,117145.00,per Annum,0.00,-7184.51,0.00,7153.63,1178.52
1762990,2017,DEPARTMENT OF SANITATION,KHAN,RICHARD,M,10/25/2004,BROOKLYN,SUPERVISOR ...,CEASED,96916.00,per Annum,0.00,-7056.83,0.00,0.00,10859.63
1563981,2014,NYC HOUSING AUTHORITY,TOLOMELLO,SALVATORE,NaN,07/27/1998,NaN,PLASTERER ...,CEASED,324.72,per Day,0.00,-6858.35,0.00,0.00,0.00
533652,2016,NYC HOUSING AUTHORITY,O'SULLIVAN,THOMAS,F,03/21/2011,QUEENS,BRICKLAYER ...,CEASED,320.39,per Day,0.00,-6828.06,0.00,39.46,0.00
2116236,2017,NYC HOUSING AUTHORITY,ORTIZ,MIGUEL,A,08/08/2011,BRONX,MAINTENANCE WORKER ...,CEASED,224.08,per Day,0.00,-6746.75,0.00,0.00,0.00
1925241,2017,DEPT OF ED PEDAGOGICAL,SMITH,KAREN,M,09/03/2002,MANHATTAN,TEACHER ...,CEASED,39325.00,per Annum,0.00,-6500.00,0.00,0.00,0.00
1563423,2014,NYC HOUSING AUTHORITY,SFERRUZZA,LOUIS,NaN,05/12/1997,NaN,CARETAKER ...,CEASED,39019.00,per Annum,0.00,-6488.67,0.00,0.00,0.00
1114896,2015,NYC HOUSING AUTHORITY,WILLIAMS,PATRICE,NaN,02/03/1988,MANHATTAN,RESIDENT BUILDING SUPERINTENDENT ...,CEASED,81337.00,per Annum,0.00,-6476.01,0.00,0.00,79.80
529918,2016,NYC HOUSING AUTHORITY,HUERTAS,LUCAS,NaN,06/20/1994,BROOKLYN,CARETAKER ...,CEASED,40201.00,per Annum,0.00,-6420.72,0.00,249.09,18.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4087,2016,BRONX DISTRICT ATTORNEY,DREHER,ROBERT,L,10/15/1973,BRONX,ASSISTANT DISTRICT ATTORNEY ...,CEASED,199900.00,per Annum,1679.00,292201.96,0.00,0.00,0.00
1533183,2014,DEPARTMENT OF TRANSPORTATION,PERAHIA,HENRY,D,01/23/1989,NaN,ADMINISTRATIVE ENGINEER ...,CEASED,186088.00,per Annum,1073.00,292615.23,0.00,0.00,500.00
1187633,2014,OFFICE OF LABOR RELATIONS,HANLEY,JAMES,NaN,09/17/1973,NaN,COMMISSIONER OF LABOR RELATIONS ...,CEASED,205180.00,per Annum,1080.00,297093.12,0.00,0.00,0.00
2121772,2017,OFFICE OF THE ACTUARY,CHAN,SHERRY,S,05/18/2015,MANHATTAN,CHIEF ACTUARY ...,ACTIVE,290331.00,per Annum,1825.00,298754.84,0.00,0.00,250.00
684151,2015,DEPARTMENT OF CORRECTION,HINNANT,HERBERT,L,12/06/1991,BROOKLYN,CORRECTION OFFICER ...,CEASED,46248.00,per Annum,0.00,300000.00,0.00,0.00,0.00
682505,2015,DEPARTMENT OF CORRECTION,EBANKS,EDWARD,V,09/27/1990,BROOKLYN,CORRECTION OFFICER ...,CEASED,46248.00,per Annum,0.00,300000.00,0.00,0.00,0.00
1761421,2017,DEPARTMENT OF SANITATION,GIATTINO,JOSEPH,J,08/23/1971,QUEENS,SUPERVISOR OF MECHANICS ...,ACTIVE,159327.00,per Annum,2085.72,301965.31,0.00,0.00,4594.23
550001,2015,DISTRICT ATTORNEY RICHMOND COU,CARARA,RONALD,NaN,01/04/2004,RICHMOND,ADMINISTRATIVE STAFF ANALYST ...,CEASED,155053.00,per Annum,1600.00,304606.62,0.00,0.00,1000.00
820217,2015,DEPT OF ED PEDAGOGICAL,DOWNING,RAQUEL,S,09/02/1997,MANHATTAN,ASSISTANT PRINCIPAL ...,ACTIVE,106537.00,per Annum,0.00,306846.19,0.00,0.00,1000.00
146395,2016,DEPARTMENT OF CORRECTION,PERRINO,JAMES,P,07/06/1989,QUEENS,WARDEN ...,CEASED,191770.00,per Annum,1262.85,316552.04,0.00,0.00,0.00
2173048,2017,POLICE DEPARTMENT,OBYRNE,BRIAN,M,07/01/2004,MANHATTAN,POLICE OFFICER ...,ACTIVE,85292.00,per Annum,2051.43,325867.35,7.82,531.69,44982.36
509775,2016,HRA/DEPT OF SOCIAL SERVICES,ELBAZ,MEYER,NaN,08/15/1977,BROOKLYN,DIRECTOR OF INFORMATION SERVICES ...,CEASED,192587.00,per Annum,1385.00,326378.68,0.00,0.00,0.00
1928065,2017,DEPT OF ED PEDAGOGICAL,SUKER,DAVID,P,09/08/1998,MANHATTAN,TEACHER ...,ACTIVE,98458.00,per Annum,0.00,326609.68,0.00,0.00,38.04
540115,2016,OFFICE OF THE COMPTROLLER,EVANS,SCOTT,C,07/14/2014,MANHATTAN,PENSION INVESTMENT ADVISOR ...,ACTIVE,350000.00,per Annum,1830.00,332081.46,0.00,0.00,0.00
1728401,2017,DEPARTMENT OF CORRECTION,GRABOWSKI,GREGORY,G,06/01/2000,QUEENS,CORRECTION OFFICER ...,ACTIVE,82808.00,per Annum,2085.72,334891.10,60.55,1585.68,37427.32
688844,2015,DEPARTMENT OF CORRECTION,SCOTT,MARK,A,12/15/1985,QUEENS,WARDEN ...,CEASED,187093.00,per Annum,1572.57,337063.11,0.00,0.00,1000.00
13861,2016,POLICE DEPARTMENT,CARIONE,DANIEL,A,07/03/1989,BROOKLYN,CAPTAIN D/A DEPUTY INSPECTOR,ACTIVE,160565.00,per Annum,2091.42,355861.22,0.00,0.00,95960.96
2122085,2017,OFFICE OF THE COMPTROLLER,EVANS,SCOTT,C,07/14/2014,MANHATTAN,PENSION INVESTMENT ADVISOR ...,ACTIVE,350000.00,per Annum,1825.00,362416.04,0.00,0.00,0.00
686919,2015,DEPARTMENT OF CORRECTION,NICHOLS,MICHAEL,L,08/03/1989,BROOKLYN,CORRECTION OFFICER ...,CEASED,46248.00,per Annum,0.00,379000.00,0.00,0.00,0.00
1632134,2014,Kings DA,VECCHIONE,MICHAEL,F,01/06/1992,NaN,ASSISTANT DISTRICT ATTORNEY ...,CEASED,189000.00,per Annum,828.00,379138.59,0.00,0.00,250.00
688116,2015,DEPARTMENT OF CORRECTION,RIVERA,ALBERTO,NaN,12/22/1988,BROOKLYN,CORRECTION OFFICER ...,CEASED,51474.00,per Annum,0.00,405000.00,0.00,0.00,0.00
149584,2016,DEPARTMENT OF CORRECTION,VAZQUEZ,VICTOR,NaN,07/13/1983,QUEENS,WARDEN ...,CEASED,191770.00,per Annum,862.85,445490.73,0.00,0.00,0.00
865432,2015,DEPT OF ED PEDAGOGICAL,NIGRO,LISA,M,09/13/2004,MANHATTAN,TEACHER ...,ACTIVE,82900.00,per Annum,0.00,447963.20,0.00,0.00,307.27
688177,2015,DEPARTMENT OF CORRECTION,RIVERA-BEY,PEDRO,NaN,05/19/1985,BROOKLYN,CORRECTION OFFICER ...,CEASED,46248.00,per Annum,0.00,467000.00,0.00,0.00,0.00
679454,2015,DEPARTMENT OF CORRECTION,ABDALLAH,HASSAN,B,03/02/1989,BROOKLYN,CORRECTION OFFICER ...,CEASED,46248.00,per Annum,0.00,467000.00,0.00,0.00,0.00
618149,2015,BOARD OF CORRECTION,TRIPP,SHERIE,NaN,01/09/1989,MANHATTAN,CORRECTIONAL STANDARDS REVIEW SPECIALIST ...,ACTIVE,61157.00,per Annum,1870.00,476550.65,0.00,0.00,1751.66
59528,2016,POLICE DEPARTMENT,SCHOOLCRAFT,ADRIAN,P,07/01/2002,MANHATTAN,POLICE OFFICER,CEASED,78026.00,per Annum,240.00,487277.63,0.00,52571.02,100355.84
690358,2015,DEPARTMENT OF CORRECTION,WATSON,ROBERT,A,07/06/1989,BROOKLYN,CAPTAIN ...,CEASED,50446.00,per Annum,0.00,488000.00,0.00,0.00,0.00
1505855,2014,DEPT OF HEALTH/MENTAL HYGIENE,FRANKLIN,DOLORES,M,07/07/2003,NaN,"DIRECTOR, MEDICAL AFFAIRS ...",CEASED,144772.00,per Annum,0.00,541544.90,0.00,0.00,0.00
192014,2016,DEPARTMENT OF TRANSPORTATION,TIPALDO,JOHN,M,01/09/1984,QUEENS,ADMINISTRATIVE ENGINEER ...,ACTIVE,176702.00,per Annum,1830.00,672308.86,0.00,0.00,422.40

Create a new column with a constant

In [18]:
payroll_df['Constant'] = 0

In [19]:
payroll_df

,Fiscal Year,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay,Constant
0,2016,DISTRICT ATTORNEY-MANHATTAN,ABA'AHMID,RAHASHEEM,E,07/14/2003,MANHATTAN,COMMUNITY ASSOCIATE ...,ACTIVE,47678.00,per Annum,1830.00,47166.03,2.25,57.28,0.00,0
1,2016,DISTRICT ATTORNEY-MANHATTAN,ABENSUR,MARGARET,NaN,06/12/1995,MANHATTAN,ADMINISTRATIVE ACCOUNTANT ...,ACTIVE,119959.00,per Annum,1831.00,119042.50,0.00,0.00,0.00,0
2,2016,DISTRICT ATTORNEY-MANHATTAN,ABOUNAOUM,ANDREA,L,10/11/2011,MANHATTAN,COMMUNITY ASSOCIATE ...,ON LEAVE,39966.00,per Annum,1181.68,27452.62,1.00,21.34,33.00,0
3,2016,DISTRICT ATTORNEY-MANHATTAN,ABRAHAM,JONATHAN,J,12/01/2014,MANHATTAN,COMPUTER SYSTEMS MANAGER ...,ACTIVE,116000.00,per Annum,1831.00,115104.57,0.00,0.00,0.00,0
4,2016,DISTRICT ATTORNEY-MANHATTAN,ABRAMS,JOSEPH,NaN,05/21/2015,MANHATTAN,COLLEGE AIDE ...,CEASED,1.00,per Hour,0.00,3500.00,0.00,0.00,0.00,0
5,2016,DISTRICT ATTORNEY-MANHATTAN,ABREU,JENNIFER,NaN,09/04/2012,MANHATTAN,ASSISTANT DISTRICT ATTORNEY ...,ACTIVE,71500.00,per Annum,1831.00,71967.34,0.00,0.00,0.00,0
6,2016,DISTRICT ATTORNEY-MANHATTAN,ABREU,JUAN,D,09/04/2007,MANHATTAN,ASSISTANT DISTRICT ATTORNEY ...,ACTIVE,88000.00,per Annum,1831.00,87614.01,0.00,0.00,750.00,0
7,2016,DISTRICT ATTORNEY-MANHATTAN,ACEVEDO,JENNIFER,NaN,06/06/2016,MANHATTAN,COLLEGE AIDE ...,ACTIVE,1.00,per Hour,0.00,500.00,0.00,0.00,0.00,0
8,2016,DISTRICT ATTORNEY-MANHATTAN,ACOCELLA,MATTHEW,J,09/02/2014,MANHATTAN,COMMUNITY ASSOCIATE ...,CEASED,41000.00,per Annum,349.00,9507.15,0.00,0.00,0.00,0
9,2016,DISTRICT ATTORNEY-MANHATTAN,ACOSTA,RITA,E,05/31/1978,MANHATTAN,PRINCIPAL ADMINISTRATIVE ASSOCIATE,ACTIVE,66035.00,per Annum,1830.00,64357.12,0.00,0.00,3824.72,0
10,2016,DISTRICT ATTORNEY-MANHATTAN,ADAMS,KATHERINE,J,04/22/2013,MANHATTAN,COMMUNITY ASSOCIATE ...,CEASED,38869.00,per Annum,200.70,6073.13,0.00,0.00,8.25,0
11,2016,DISTRICT ATTORNEY-MANHATTAN,ADAMS,NEERESHA,NaN,08/25/2014,MANHATTAN,COMMUNITY ASSOCIATE ...,ACTIVE,42075.00,per Annum,1830.00,39895.79,0.00,0.00,74.25,0
12,2016,DISTRICT ATTORNEY-MANHATTAN,ADEGBORO,OYINDAMOLA,F,01/13/2014,MANHATTAN,COMMUNITY COORDINATOR ...,ACTIVE,66625.00,per Annum,1830.00,65909.63,0.00,0.00,33.00,0
13,2016,DISTRICT ATTORNEY-MANHATTAN,AGGARWAL,SANCHITA,J,03/28/2005,MANHATTAN,PRINCIPAL ACCOUNTANT INVESTIGATOR ...,ACTIVE,112592.00,per Annum,1831.00,111806.82,0.00,0.00,500.00,0
14,2016,DISTRICT ATTORNEY-MANHATTAN,AGUILAR,YAMIRA,NaN,11/09/2009,MANHATTAN,COMMUNITY ASSOCIATE ...,ACTIVE,52548.00,per Annum,1830.00,51890.77,716.25,25943.55,747.93,0
15,2016,DISTRICT ATTORNEY-MANHATTAN,AGUIRRE,JORDAN,NaN,05/21/2015,MANHATTAN,COLLEGE AIDE ...,CEASED,1.00,per Hour,0.00,3500.00,0.00,0.00,0.00,0
16,2016,DISTRICT ATTORNEY-MANHATTAN,AHMETAJ,ARTEMIS,NaN,04/28/2014,MANHATTAN,COMMUNITY ASSISTANT ...,ACTIVE,43299.00,per Annum,1830.00,40052.01,51.75,1413.40,526.11,0
17,2016,DISTRICT ATTORNEY-MANHATTAN,AHN,HELEN,H,09/07/2004,MANHATTAN,ASSISTANT DISTRICT ATTORNEY ...,ACTIVE,102500.00,per Annum,1076.00,59023.02,0.00,0.00,0.00,0
18,2016,DISTRICT ATTORNEY-MANHATTAN,ALCAIDE,SANDRA,NaN,05/21/2015,MANHATTAN,COLLEGE AIDE ...,CEASED,1.00,per Hour,0.00,3500.00,0.00,0.00,0.00,0
19,2016,DISTRICT ATTORNEY-MANHATTAN,ALCANTARA,DANIEL,NaN,01/19/2007,MANHATTAN,COMMUNITY ASSOCIATE ...,ACTIVE,40299.00,per Annum,1830.00,39866.21,0.00,0.00,0.00,0
20,2016,DISTRICT ATTORNEY-MANHATTAN,ALEXANDER,ERIN,L,09/02/2014,MANHATTAN,ASSISTANT DISTRICT ATTORNEY ...,ACTIVE,78000.00,per Annum,1509.00,64498.36,0.00,0.00,1750.00,0
21,2016,DISTRICT ATTORNEY-MANHATTAN,ALFLEN,PAUL,R,09/21/2008,MANHATTAN,CARPENTER ...,ACTIVE,370.16,per Day,1830.00,139072.14,408.75,50546.28,5060.37,0
22,2016,DISTRICT ATTORNEY-MANHATTAN,ALI,SHEHARYAR,NaN,06/06/2016,MANHATTAN,COLLEGE AIDE ...,ACTIVE,1.00,per Hour,0.00,1000.00,0.00,0.00,0.00,0
23,2016,DISTRICT ATTORNEY-MANHATTAN,ALI,SYEED,A,03/02/2009,MANHATTAN,ELECTRICIAN'S HELPER ...,ACTIVE,217.70,per Day,1830.00,56602.00,173.75,8991.82,7424.72,0
24,2016,DISTRICT ATTORNEY-MANHATTAN,AL-KAABAH II,JEFFREY,I,06/08/2015,MANHATTAN,COMMUNITY ASSOCIATE ...,ACTIVE,53366.00,per Annum,1829.75,46271.84,276.50,7757.06,755.84,0
25,2016,DISTRICT ATTORNEY-MANHATTAN,NaN,NaN,NaN,08/06/2001,MANHATTAN,RACKETS INVESTIGATOR,CEASED,59945.00,per Annum,0.00,7412.58,0.00,13.01,340.12,0
26,2016,DISTRICT ATTORNEY-MANHATTAN,ALKHAFAJEE,ABEER,K,08/16/2010,MANHATTAN,COMMUNITY ASSOCIATE ...,CEASED,45985.00,per Annum,38.10,4661.03,1.00,169.90,94.40,0
27,2016,DISTRICT ATTORNEY-MANHATTAN,ALKHAFAJEE,SHAIMAA,NaN,01/14/2008,MANHATTAN,COMMUNITY ASSISTANT ...,ACTIVE,36154.00,per Annum,1830.00,35765.73,0.00,0.00,0.00,0
28,2016,DISTRICT ATTORNEY-MANHATTAN,ALLEN,BENNETT,L,10/20/2014,MANHATTAN,COMMUNITY COORDINATOR ...,ACTIVE,65600.00,per Annum,1830.00,64895.59,0.00,0.00,99.50,0
29,2016,DISTRICT ATTORNEY-MANHATTAN,ALLEN,ROBERT,K,01/21/1980,MANHATTAN,CLERICAL ASSOCIATE,ACTIVE,56017.00,per Annum,1830.00,55411.18,0.00,0.00,4424.50,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2194458,2017,DISTRICT ATTORNEY-SPECIAL NARC,BACH,CAROL,M,02/06/1995,MANHATTAN,REPORTER/ STENOGRAPHER ...,ACTIVE,76906.00,per Annum,745.00,35037.96,0.00,0.00,1392.26,0
2194459,2017,DISTRICT ATTORNEY-SPECIAL NARC,ARNOLD,JODI,A,06/02/2008,MANHATTAN,REPORTER/ STENOGRAPHER ...,ACTIVE,70107.00,per Annum,1795.00,78899.33,0.00,293.87,1034.00,0
2194460,2017,DISTRICT ATTORNEY-SPECIAL NARC,MONESTIME,MIREILLE,NaN,11/28/1988,MANHATTAN,REPORTER/ STENOGRAPHER ...,ACTIVE,81465.00,per Annum,1795.00,92825.55,0.00,0.00,5234.62,0
2194461,2017,DISTRICT ATTORNEY-SPECIAL NARC,PALMER,REVA,A,04/08/1985,MANHATTAN,REPORTER/ STENOGRAPHER ...,ACTIVE,81465.00,per Annum,1795.00,92392.05,0.00,0.00,5242.87,0
2194462,2017,DISTRICT ATTORNEY-SPECIAL NARC,GIERAS,SUSAN,NaN,05/09/2016,MANHATTAN,REPORTER/ STENOGRAPHER ...,ACTIVE,53930.00,per Annum,1795.00,61257.09,0.00,0.00,0.00,0
2194463,2017,DISTRICT ATTORNEY-SPECIAL NARC,AKOTO,AKUA,P,02/22/1982,MANHATTAN,SECRETARY ...,ACTIVE,72420.00,per Annum,1795.00,78504.22,0.00,0.00,4777.75,0
2194464,2017,DISTRICT ATTORNEY-SPECIAL NARC,MCNEILL,BELINDA,D,05/28/1991,MANHATTAN,SECRETARY ...,ACTIVE,62141.00,per Annum,1795.00,66533.67,0.00,0.00,4794.25,0
2194465,2017,DISTRICT ATTORNEY-SPECIAL NARC,MOULTRIE,HYARLIEN,NaN,12/04/2000,MANHATTAN,SECRETARY ...,ACTIVE,88799.00,per Annum,1795.00,95355.97,0.00,0.00,4777.75,0
2194466,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,NaN,01/03/2000,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,75281.00,per Annum,2051.43,85707.57,59.00,3458.71,2700.42,0
2194467,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,A,10/06/2014,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,62330.00,per Annum,2051.43,72345.61,9.00,425.61,3649.49,0
2194468,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,A,06/06/2016,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,59920.00,per Annum,2051.43,62875.62,0.00,0.00,3707.68,0
2194469,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,V,01/22/2002,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,82451.00,per Annum,2051.43,90699.68,0.00,0.00,3648.99,0
2194470,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,J,05/01/2001,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,88609.00,per Annum,2051.43,99463.33,0.00,0.00,3624.24,0
2194471,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,NaN,02/03/2014,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,65202.00,per Annum,2051.43,75310.50,63.00,3442.18,3624.24,0
2194472,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,R,11/18/1996,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,CEASED,82032.00,per Annum,931.43,50750.67,0.00,0.00,1744.74,0
2194473,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,K,09/05/2006,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,78643.00,per Annum,2051.43,86779.58,0.00,0.00,3624.24,0
2194474,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,M,07/05/1989,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,CEASED,78342.00,per Annum,1483.43,110014.31,0.00,0.00,2671.02,0
2194475,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,R,02/27/1989,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,79275.00,per Annum,2051.43,89827.42,43.00,3361.40,3624.24,0
2194476,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,NaN,10/13/2015,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,60000.00,per Annum,2051.43,64925.95,8.00,1283.22,4743.09,0
2194477,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,NaN,02/23/1998,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,CEASED,78634.00,per Annum,1515.43,89040.81,0.00,0.00,2724.80,0
2194478,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,NaN,02/28/1994,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,89824.00,per Annum,2051.43,100717.56,0.00,0.00,3624.24,0
2194479,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,W,08/02/1982,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,CEASED,89443.00,per Annum,0.00,8620.39,0.00,0.00,133.88,0
2194480,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,J,02/07/2017,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,60000.00,per Annum,792.00,22783.69,0.00,0.00,8.25,0
2194481,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,K,11/03/2014,MANHATTAN,SENIOR RACKETS INVESTIGATOR ...,ACTIVE,59099.00,per Annum,2051.43,69010.10,205.00,9713.32,84.91,0
2194482,2017,DISTRICT ATTORNEY-SPECIAL NARC,BRENNAN,BRIDGET,G,01/27/1992,MANHATTAN,SPECIAL ASSISTANT DISTRICT ATTORNEY ...,ACTIVE,206416.00,per Annum,1795.00,221466.24,0.00,0.00,0.00,0
2194483,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,G,10/02/2006,MANHATTAN,SUPERVISING RACKETS INVESTIGATOR,ACTIVE,80643.00,per Annum,2051.43,87321.90,113.00,7667.53,3624.24,0
2194484,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,C,01/18/2000,MANHATTAN,SUPERVISING RACKETS INVESTIGATOR,ACTIVE,88883.00,per Annum,2051.43,99746.21,117.00,9491.90,3624.24,0
2194485,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,NaN,03/17/1997,MANHATTAN,SUPERVISING RACKETS INVESTIGATOR,ACTIVE,89686.00,per Annum,2051.43,96646.24,63.00,4937.42,3624.24,0
2194486,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,J,04/19/1993,MANHATTAN,SUPERVISING RACKETS INVESTIGATOR,ACTIVE,94245.00,per Annum,2051.43,105281.70,22.00,1544.83,3624.24,0
2194487,2017,DISTRICT ATTORNEY-SPECIAL NARC,XXX,XXX,L,02/10/1992,MANHATTAN,SUPERVISING RACKETS INVESTIGATOR,CEASED,89780.00,per Annum,1235.43,78923.55,160.00,12509.95,2388.87,0

Get familiar with datetime data type and operations (https://pymotw.com/2/datetime/)

In [2]:
attack_dates = ['7/2/2011', '8/6/2012', '11/13/2013', '5/26/2011', '5/2/2001']

In [18]:
import datetime
[datetime.datetime.strptime(x, '%m/%d/%Y') for x in attack_dates]

[datetime.datetime(2011, 7, 2, 0, 0),
 datetime.datetime(2012, 8, 6, 0, 0),
 datetime.datetime(2013, 11, 13, 0, 0),
 datetime.datetime(2011, 5, 26, 0, 0),
 datetime.datetime(2001, 5, 2, 0, 0)]

In [17]:
from datetime import datetime
[datetime.strptime(x, '%m/%d/%Y') for x in attack_dates]

[datetime.datetime(2011, 7, 2, 0, 0),
 datetime.datetime(2012, 8, 6, 0, 0),
 datetime.datetime(2013, 11, 13, 0, 0),
 datetime.datetime(2011, 5, 26, 0, 0),
 datetime.datetime(2001, 5, 2, 0, 0)]

In [49]:
test_df = pd.read_csv('mytest_csvfile.csv')
test_df

,Fiscal Year,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay
0,2016,DISTRICT ATTORNEY-MANHATTAN,ABA'AHMID,RAHASHEEM,E,07/14/2003,MANHATTAN,COMMUNITY ASSOCIATE ...,ACTIVE,$47678.00,per Annum,1830.00,$47166.03,2.25,$57.28,$0.00
1,2016,DISTRICT ATTORNEY-MANHATTAN,ABENSUR,MARGARET,NaN,06/12/1995,MANHATTAN,ADMINISTRATIVE ACCOUNTANT ...,ACTIVE,$119959.00,per Annum,1831.00,$119042.50,0.00,$0.00,$0.00
2,2016,DISTRICT ATTORNEY-MANHATTAN,ABOUNAOUM,ANDREA,L,10/11/2011,MANHATTAN,COMMUNITY ASSOCIATE ...,ON LEAVE,$39966.00,per Annum,1181.68,$27452.62,1.00,$21.34,$33.00
3,2016,DISTRICT ATTORNEY-MANHATTAN,ABRAHAM,JONATHAN,J,12/01/2014,MANHATTAN,COMPUTER SYSTEMS MANAGER ...,ACTIVE,$116000.00,per Annum,1831.00,$115104.57,0.00,$0.00,$0.00
4,2016,DISTRICT ATTORNEY-MANHATTAN,ABRAMS,JOSEPH,NaN,05/21/2015,MANHATTAN,COLLEGE AIDE ...,CEASED,$1.00,per Hour,0.00,$3500.00,0.00,$0.00,$0.00

In [43]:
[datetime.datetime.strptime(x, '%m/%d/%Y') for x in test_df['Agency Start Date']]

[datetime.datetime(2003, 7, 14, 0, 0),
 datetime.datetime(1995, 6, 12, 0, 0),
 datetime.datetime(2011, 10, 11, 0, 0),
 datetime.datetime(2014, 12, 1, 0, 0),
 datetime.datetime(2015, 5, 21, 0, 0)]

In [52]:
[parse(x) for x in test_df['Agency Start Date'].tolist()]

NameError: name 'parse' is not defined

In [53]:
test_df['Agency Start Date'] = pd.Series(datetime.datetime.strptime(x, '%m/%d/%Y') for x in test_df['Agency Start Date'])

In [54]:
test_df.dtypes

Fiscal Year                            int64
Agency Name                           object
Last Name                             object
First Name                            object
Mid Init                              object
Agency Start Date             datetime64[ns]
Work Location Borough                 object
Title Description                     object
Leave Status as of June 30            object
Base Salary                           object
Pay Basis                             object
Regular Hours                        float64
Regular Gross Paid                    object
OT Hours                             float64
Total OT Paid                         object
Total Other Pay                       object
dtype: object

Count the number of agencies

In [12]:
len(set(payroll_df['Agency Name'].tolist()))

165

Data aggregation. For example, compute average base salary of every agency in a fiscal year, or count the number of employees of each agency in a fiscal year.

In [20]:
set(payroll_df['Agency Name'].tolist())

{"ADMIN FOR CHILDREN'S SVCS     ",
 'ADMIN TRIALS AND HEARINGS     ',
 'BOARD OF CORRECTION           ',
 'BOARD OF CORRECTIONS          ',
 'BOARD OF ELECTION             ',
 'BOARD OF ELECTION POLL WORKERS',
 'BOROUGH PRESIDENT-BRONX       ',
 'BOROUGH PRESIDENT-BROOKLYN    ',
 'BOROUGH PRESIDENT-QUEENS      ',
 'BOROUGH PRESIDENT-STATEN IS   ',
 'BRONX COMMUNITY BOARD #1      ',
 'BRONX COMMUNITY BOARD #10     ',
 'BRONX COMMUNITY BOARD #11     ',
 'BRONX COMMUNITY BOARD #12     ',
 'BRONX COMMUNITY BOARD #2      ',
 'BRONX COMMUNITY BOARD #3      ',
 'BRONX COMMUNITY BOARD #4      ',
 'BRONX COMMUNITY BOARD #5      ',
 'BRONX COMMUNITY BOARD #6      ',
 'BRONX COMMUNITY BOARD #7      ',
 'BRONX COMMUNITY BOARD #8      ',
 'BRONX COMMUNITY BOARD #9      ',
 'BRONX DISTRICT ATTORNEY       ',
 'BROOKLYN COMMUNITY BOARD #1   ',
 'BROOKLYN COMMUNITY BOARD #10  ',
 'BROOKLYN COMMUNITY BOARD #11  ',
 'BROOKLYN COMMUNITY BOARD #12  ',
 'BROOKLYN COMMUNITY BOARD #13  ',
 'BROOKLYN COMMUNITY BOARD #14  ',
 'BROOKLYN COMMUNITY BOARD #15  ',
 'BROOKLYN COMMUNITY BOARD #16  ',
 'BROOKLYN COMMUNITY BOARD #17  ',
 'BROOKLYN COMMUNITY BOARD #18  ',
 'BROOKLYN COMMUNITY BOARD #2   ',
 'BROOKLYN COMMUNITY BOARD #3   ',
 'BROOKLYN COMMUNITY BOARD #4   ',
 'BROOKLYN COMMUNITY BOARD #5   ',
 'BROOKLYN COMMUNITY BOARD #6   ',
 'BROOKLYN COMMUNITY BOARD #7   ',
 'BROOKLYN COMMUNITY BOARD #8   ',
 'BROOKLYN COMMUNITY BOARD #9   ',
 'BUSINESS INTEGRITY COMMISSION ',
 'Bronx DA       ',
 'CAMPAIGN FINANCE BOARD        ',
 'CITY CLERK                    ',
 'CITY COUNCIL                  ',
 'CIVIL SERVICE COMMISSION      ',
 'CIVILIAN COMPLAINT REVIEW BD  ',
 'COMMUNITY COLLEGE (BRONX)     ',
 'COMMUNITY COLLEGE (HOSTOS)    ',
 'COMMUNITY COLLEGE (KINGSBORO) ',
 'COMMUNITY COLLEGE (LAGUARDIA) ',
 'COMMUNITY COLLEGE (MANHATTAN) ',
 'COMMUNITY COLLEGE (QUEENSBORO)',
 'CONFLICTS OF INTEREST BOARD   ',
 'CONSUMER AFFAIRS              ',
 'CULTURAL AFFAIRS              ',
 'CUNY CENTRAL OFFICE           ',
 'DEPARTMENT FOR THE AGING      ',
 'DEPARTMENT OF BUILDINGS       ',
 'DEPARTMENT OF BUSINESS SERV.  ',
 'DEPARTMENT OF CITY PLANNING   ',
 'DEPARTMENT OF CORRECTION      ',
 'DEPARTMENT OF EDUCATION ADMIN ',
 'DEPARTMENT OF FINANCE         ',
 'DEPARTMENT OF INVESTIGATION   ',
 'DEPARTMENT OF JUVENILE JUSTICE',
 'DEPARTMENT OF PROBATION       ',
 'DEPARTMENT OF SANITATION      ',
 'DEPARTMENT OF TRANSPORTATION  ',
 'DEPT OF CITYWIDE ADMIN SVCS   ',
 'DEPT OF ED HRLY SUPPORT STAFF ',
 'DEPT OF ED PARA PROFESSIONALS ',
 'DEPT OF ED PEDAGOGICAL        ',
 'DEPT OF ED PER DIEM TEACHERS  ',
 'DEPT OF ED PER SESSION TEACHER',
 'DEPT OF ENVIRONMENT PROTECTION',
 'DEPT OF HEALTH/MENTAL HYGIENE ',
 'DEPT OF INFO TECH & TELECOMM  ',
 'DEPT OF PARKS & RECREATION    ',
 'DEPT OF RECORDS & INFO SERVICE',
 'DEPT OF YOUTH & COMM DEV SRVS ',
 'DEPT. OF DESIGN & CONSTRUCTION',
 'DEPT. OF HOMELESS SERVICES    ',
 'DISTRICT ATTORNEY KINGS COUNTY',
 'DISTRICT ATTORNEY QNS COUNTY  ',
 'DISTRICT ATTORNEY RICHMOND COU',
 'DISTRICT ATTORNEY-MANHATTAN   ',
 'DISTRICT ATTORNEY-SPECIAL NARC',
 'DISTRICTING COMMISSION        ',
 'DOE CUSTODIAL PAYROL          ',
 'EQUAL EMPLOY PRACTICES COMM   ',
 'FINANCIAL INFO SVCS AGENCY    ',
 'FIRE DEPARTMENT               ',
 'GUTTMAN COMMUNITY COLLEGE     ',
 'HOUSING PRESERVATION & DVLPMNT',
 'HRA/DEPT OF SOCIAL SERVICES   ',
 'HUMAN RIGHTS COMMISSION       ',
 'HUNTER COLLEGE HIGH SCHOOL    ',
 'INDEPENDENT BUDGET OFFICE     ',
 'Kings DA',
 'LANDMARKS PRESERVATION COMM   ',
 'LAW DEPARTMENT                ',
 'MANHATTAN COMMUNITY BOARD #1  ',
 'MANHATTAN COMMUNITY BOARD #10 ',
 'MANHATTAN COMMUNITY BOARD #11 ',
 'MANHATTAN COMMUNITY BOARD #12 ',
 'MANHATTAN COMMUNITY BOARD #2  ',
 'MANHATTAN COMMUNITY BOARD #3  ',
 'MANHATTAN COMMUNITY BOARD #4  ',
 'MANHATTAN COMMUNITY BOARD #5  ',
 'MANHATTAN COMMUNITY BOARD #6  ',
 'MANHATTAN COMMUNITY BOARD #7  ',
 'MANHATTAN COMMUNITY BOARD #8  ',
 'MANHATTAN COMMUNITY BOARD #9  ',
 'MAYORS OFFICE OF CONTRACT SVCS',
 'MUNICIPAL WATER FIN AUTHORITY ',
 'Manhattan DA   ',
 "NYC DEPT OF VETERANS' SERVICES",
 'NYC EMPLOYEES RETIREMENT SYS  ',
 'NYC HOUSING AUTHORITY         ',
 'NYC POLICE PENSION FUND       ',
 'OFF OF PAYROLL ADMINISTRATION ',
 'OFFICE OF COLLECTIVE BARGAININ',
 'OFFICE OF EMERGENCY MANAGEMENT',
 'OFFICE OF LABOR RELATIONS     ',
 'OFFICE OF MANAGEMENT & BUDGET ',
 'OFFICE OF THE ACTUARY         ',
 'OFFICE OF THE COMPTROLLER     ',
 'OFFICE OF THE MAYOR           ',
 'PERSONNEL MONITORS            ',
 'POLICE DEPARTMENT',
 'POLICE DEPARTMENT             ',
 'PRESIDENT BOROUGH OF MANHATTAN',
 'PUBLIC ADMINISTRATOR-BRONX    ',
 'PUBLIC ADMINISTRATOR-KINGS    ',
 'PUBLIC ADMINISTRATOR-NEW YORK ',
 'PUBLIC ADMINISTRATOR-QUEENS   ',
 'PUBLIC ADMINISTRATOR-RICHMOND ',
 'PUBLIC ADVOCATE               ',
 'PUBLIC SERVICE CORPS          ',
 'Police Department',
 'QUEENS COMMUNITY BOARD #1     ',
 'QUEENS COMMUNITY BOARD #10    ',
 'QUEENS COMMUNITY BOARD #11    ',
 'QUEENS COMMUNITY BOARD #12    ',
 'QUEENS COMMUNITY BOARD #13    ',
 'QUEENS COMMUNITY BOARD #14    ',
 'QUEENS COMMUNITY BOARD #2     ',
 'QUEENS COMMUNITY BOARD #3     ',
 'QUEENS COMMUNITY BOARD #4     ',
 'QUEENS COMMUNITY BOARD #5     ',
 'QUEENS COMMUNITY BOARD #6     ',
 'QUEENS COMMUNITY BOARD #7     ',
 'QUEENS COMMUNITY BOARD #8     ',
 'QUEENS COMMUNITY BOARD #9     ',
 'Queens DA  ',
 'Richmond DA',
 'STATEN ISLAND COMMUNITY BD #1 ',
 'STATEN ISLAND COMMUNITY BD #2 ',
 'STATEN ISLAND COMMUNITY BD #3 ',
 'Spec Narcs-DA',
 'TAX COMMISSION                ',
 'TAXI & LIMOUSINE COMMISSION   ',
 'TEACHERS RETIREMENT SYSTEM    '}